nome = str(input('Digite o nome do cliente: '))
vencimento = str(input('Digite o dia de vencimento: '))
mesvencimento = str(input('Digite o mês de vencimento: '))
valor = input('Digite o valor da fatura: ')
print('Olá, ', nome)
print('A sua fatura com vencimento em', vencimento, ' de ', mesvencimento, ' no valor de R$ ', valor, ' está fechada')
